ClassLength:
  # It's not worth bending over backwards to avoid long classes.
  Enabled: false
CollectionMethods:
  PreferredMethods:
    collect: 'map'
    reduce: 'inject'
    detect: 'find'
    find_all: 'select'
CyclomaticComplexity:
  Enabled: false
Documentation:
  # TODO: We need to add a bunch of docs before we can enable this.
  Enabled: false
HashSyntax:
  EnforcedStyle: hash_rockets
IfUnlessModifier:
  Enabled: false
LineLength:
  Enabled: true
  Max: 160
Metrics/AbcSize:
  Enabled: false
MethodLength:
  Max: 50
  CountComments: false
ModuleFunction:
  # The module_function declaration makes methods private so it means you can't use the module as a module.
  Enabled: false
ParenthesesAroundCondition:
  AllowSafeAssignment: false
PerlBackrefs:
  Enabled: false
RaiseArgs:
  EnforcedStyle: compact
RedundantReturn:
  AllowMultipleReturnValues: true
RegexpLiteral:
  Enabled: false
SignalException:
  EnforcedStyle: only_raise
SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
StringLiterals:
  # They say to not use double quoted strings unless there is interpolation.
  # While this gives a marginal parse time speedup, it makes working with
  # strings annoying.
  Enabled: false
TrailingComma:
  Enabled: true
UnneededPercentX:
  Enabled: false
WhileUntilModifier:
  Enabled: false
